title: <p align="center"> Putri Rihana Dewi </p>

logo: "/images/pasfoto.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/putririhanadewi/">LinkedIn</a> |
  <a href="https://github.com/putririhanaa">GitHub</a>
  </p>
  
  <p align="justify">
  I am an undergraduate student of Statistics at Diponegoro University and currently in my 6th semester.
  <br><br>
  I have interest in Data Science and Data Analysis. I am currently learning Python for Data Analytics and Machine Learning. I am capable to use programming language such as Python, R, and SQL.  
  <br><br>
  </p>


theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
