title: <p align="center"> Putri Rihana Dewi </p>

logo: "/images/picture1.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/putri-rihana-dewi-8882ba221/">LinkedIn</a> |
  <a href="https://github.com/putririhanaa">GitHub</a>
  </p>
  
  <p align="justify">
  I am an undergraduate student of Statistics at Diponegoro University and am currently in my 6th semester.
  <br><br>
  I am interested in Data Science and currently learning Python for Machine Learning.
  <br><br>
  </p>


theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
