title: <p align="center"> Putri Rihana Dewi </p>

logo: "/images/Pas Foto - Putri Rihana Dewi.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/cv_eng.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/putririhanadewi/">LinkedIn</a> |
  <a href="https://github.com/putririhanaa">GitHub</a>
  </p>
  
  <p align="justify">
  Fresh Graduate of Statistics at Diponegoro University.
  <br><br>
  I have interest in Data Analysis and Risk Management. I am capable to use programming language such as Python, R, and SQL.  
  <br><br>
  </p>


theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
